# from https://gitlab.gnome.org/GNOME/console/-/blob/main/src/kgx-terminal.c?ref_type=heads#L141

[colors]
foreground = "#FFFFFF"
background = "#1F1F1F"
cursor_bg = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#1a3272"
selection_fg = "#adadad"

ansi = ["#241f31","#c01c28","#2ec27e","#f5c211","#1e78e4","#9841bb","#0ab9dc","#c0bfbc"]
brights = ["#5e5c64","#ed333b","#57e389","#f8e45c","#51a1ff","#c061cb","#4fd2fd","#f6f5f4"]
